# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8f763b2e5f901264d2a485a2b2e7b16fa22ccc77ddfe4c0ffe20bb1733d0af31146f2906e6e10e37d2ba65373babd01f2644f72d851b2963718957d6e049c8e

test:
  secret_key_base: c6fe0a0694e06f43d51c86f990f9f0706d9dc8a484e81d2fc83652f3f67ab6dc43a25b068368d48d43cc16c2d7b08c1a33be7a510ce9d4fee1cf45a42986e2bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
